development:
  adapter: postgresql
  encoding: unicode
  database: sb_development
  pool: 5
  username: root
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: sb_test
  pool: 5
  username: root
  password:
